FROM caddy:2.7-builder-alpine AS builder

RUN apk add -q --progress --update --no-cache git ca-certificates tzdata
WORKDIR /caddy
# Just leaving this here in case I ever decide to go back and not rely on raw R3 LE
# Doesn't really matter because CF now issues R1 LE anyway
RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM scratch

ENV HOME=/caddydir \
    CADDYPATH=/etc/caddy/data \
    TZ=Asia/Singapore

RUN mkdir -p /caddydir

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder --chown=1000 /caddy/caddy /caddy

COPY --chown=1000 template.html /caddydir/caddy
COPY --chown=1000 Caddyfile /caddydir/caddy

USER 1000

ENTRYPOINT ["/caddy"]
CMD ["run","--config","/caddydir/Caddyfile"]
