apiVersion: batch/v1
kind: Job
metadata:
  name: mirror-pv-cleanup
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: 
        - /bin/sh
        - -c
        - |
          for pv in {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv {{ end }}; do
            kubectl patch pv $pv -p '{"spec":{"claimRef": null}}' 2>/dev/null || echo "Skipping $pv"
          done
          echo "Done with PV cleanup - exiting in 5 seconds..."
          sleep 5
          echo "Goodbye!"
          exit 0
      restartPolicy: Never