apiVersion: batch/v1
kind: Job
metadata:
  name: mirror-pv-cleanup
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
      - name: kubectl
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
          chmod +x kubectl && \
          mv kubectl /usr/local/bin/kubectl && \
          kubectl get pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} --ignore-not-found=true && \
          kubectl patch pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} -p '{"spec":{"claimRef": null}}' || \
          true
      restartPolicy: Never