apiVersion: batch/v1
kind: Job
metadata:
  name: mirror-pv-cleanup
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true  # Add this line
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.32
        command:
        - /bin/sh
        args:
        - -c
        - |
          if kubectl get pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} --ignore-not-found=true | grep -q "{{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }}"; then
            kubectl patch pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} -p '{"spec":{"claimRef": null}}'
          else
            echo "PV not found, skipping patch"
          fi
        livenessProbe: null
        readinessProbe: null
      restartPolicy: Never