apiVersion: batch/v1
kind: Job
metadata:
  name: mirror-pv-cleanup
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
      - name: kubectl
        image: xlanor/kubectl:1.31.3
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        args:
        - -c
        - |
          kubectl get pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} --ignore-not-found=true && \
          kubectl patch pv {{ range .Values.jobs.jobSpecific }}{{ .name }}-pv{{ end }} -p '{"spec":{"claimRef": null}}' || \
          true
      restartPolicy: Never