{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- range $jobs := $.Values.jobs.jobSpecific }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $jobs.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $jobs.name }}
    app.kubernetes.io/name: {{ $jobs.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  schedule: {{ $jobs.schedule | quote }}
  concurrencyPolicy: {{ $.Values.jobs.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $.Values.jobs.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $.Values.jobs.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $.Values.global.appName }}
            cron: {{ $jobs.name }}
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          {{- if hasKey $.Values.global "serviceAccount" }}
          {{- if hasKey $.Values.global.serviceAccount "name" }}
          serviceAccountName: {{ $.Values.global.serviceAccount.name }}
          {{- else }}
          serviceAccountName: {{ $jobs.name }}
          {{- end }}
          {{- end }}
          {{- if hasKey $.Values.jobs "securityContext" }}
          {{- if $.Values.jobs.securityContext.enabled }}
          securityContext:
            {{- if $.Values.jobs.securityContext.runAsUser }}
            runAsUser: {{ $.Values.jobs.securityContext.runAsUser }}
            {{- end }}
            {{- if $.Values.jobs.securityContext.runAsGroup }}
            runAsGroup: {{ $.Values.jobs.securityContext.runAsGroup }}
            {{- end }}
            {{- if $.Values.jobs.securityContext.fsGroup }}
            fsGroup: {{ $.Values.jobs.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
          {{- end }}
          containers:
            - name: {{ $.Values.jobs.name }}
              image: "{{ $.Values.jobs.image.repository }}:{{ $.Values.jobs.image.tag }}"
              imagePullPolicy: {{ $.Values.jobs.image.pullPolicy }}
              {{- with $.Values.jobs.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $.Values.jobs.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if $jobs.command }}
              command:
                {{- toYaml $jobs.command | nindent 16 }}
              {{- end }}
              {{- with $jobs.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $.Values.jobs.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $jobs.mount }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with $.Values.jobs.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.jobs.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.jobs.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $.Values.jobs.restartPolicy }}
          {{- with $jobs.volumes }}
          volumes:
            - name: nas
              nfs:
                server: {{ .server }}
                path: {{ .path }}
                {{- if .mountOptions }}
                mountOptions:
                  {{- range .mountOptions }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
          {{- end }}
{{- end }}