name: Build and publish
on: 
  push:
    tags:
    - "*" # Running this workflow for any tag

jobs:
  push-webserver-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './webserver'
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Webserver Image'
        run: |
          docker build . -f Dockerfile-caddy --tag ghcr.io/xlanor/caddy:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/<your-GitHub-username>/caddy:${{ steps.get_version.outputs.VERSION }}
